### ISSUE TITLE
getting error after missing keyword: params upgrading rails and trailblazer

### ISSUE THREAD

**Issue by asnad** [trailblazer/trailblazer-rails#101]
Hi I have updated rails version of my project from 4.2 to 5.2.1 and yet I has to update version of trailblazer-rails from 1.0.4 to 2.1.6 now I'm getting error while running specs
`SystematicReject start should create system log entry for activated machines
     Failure/Error:
       result = SystematicReject::Start.({
         id: @systematic_reject.id
       }, {
         user: user,
         service: @service
       })
ArgumentError:
       missing keyword: params`
any help how can I make it use for previous version and with minimum changes

**Comment by apotonick** [comment]
Hi @asnad, what `trailblazer` version are you using?

**Comment by asnad** [comment]
@apotonick here are some contents from my gemfile.lock
`trailblazer (2.1.0.rc1)
      declarative
      trailblazer-macro (>= 2.1.0.rc1, < 2.2.0)
      trailblazer-macro-contract (= 2.1.0.rc1)
      trailblazer-operation
    trailblazer-activity (0.7.1)
      hirb
      trailblazer-context
    trailblazer-context (0.1.2)
    trailblazer-loader (0.1.2)
    trailblazer-macro (2.1.0.rc1)
    trailblazer-macro-contract (2.1.0.rc1)
      reform (>= 2.2.0, < 3.0.0)
    trailblazer-operation (0.4.1)
      trailblazer-activity (>= 0.7.1, < 0.8.0)
      trailblazer-context (>= 0.1.1, < 0.3.0)
    trailblazer-rails (2.1.6)
      railties (>= 4.0.0)
      trailblazer (>= 2.1.0.beta1, < 2.2.0)
      trailblazer-loader (>= 0.1.0)`

**Comment by emaglio** [comment]
Hi @asnad,
it seems you are using the **OLD** positional args API with Trailblazer 2.1
We are using kw args now so to pass `params` so the new API is:
`Op.(params: params, **options)`.

If you have many `missing keyword :params` errors maybe you want to keep trailblazer 2.0 setting version to `~> 2.0.7` and update `trailblazer-rails, '~> 1.0.10' `

**Comment by asnad** [comment]
Thanks a lot @emaglio it fixed my problem.
