### ISSUE TITLE
undefined method `run' for Controller

### ISSUE THREAD

**Issue by panicboat** [trailblazer/trailblazer-rails#113]
Could you please help me with this problem?

Steps to reproduce:
```ruby
class V1::AdministratorsController < ApplicationController
  def index
    result = Administrators::Operation::Index.call(params: params)
    logger.debug result

    run Administrators::Operation::Index, params: params do |result|
      render json: result[:model]
    end
    render json: {message: 'error'}
  end
end

app_1  | NoMethodError (undefined method `run' for #<V1::AdministratorsController:0x00005589fb1f2fe0>):
app_1  |   
app_1  | app/controllers/v1/administrators_controller.rb:6:in `index'
```

Dependencies:
```
ruby '2.7.1'
gem 'trailblazer-rails' (2.1.7)
```

Are there any imperfections in usage?
https://trailblazer.to/2.0/gems/trailblazer/2.0/rails.html#run

**Comment by seuros** [comment]
Please provide a sample app.

**Comment by panicboat** [comment]
Thanks for confirming.

This is sample app.
https://github.com/panicboat/api-administrator

Target SourceCode.
https://github.com/panicboat/api-administrator/blob/master/app/controllers/admin_controller.rb

**Comment by seuros** [comment]
Shared::ApplicationController should inherit from `ActionController::Base` or include `Trailblazer::Rails::Controller`

**Comment by panicboat** [comment]
Okay, I inherited ActionController::API.
Thank you so much!
