### ISSUE TITLE
Installing `trailblazer-rails` doesn't include `reform-rails` gem as dependency

### ISSUE THREAD

**Issue by mmhan** [trailblazer/trailblazer-rails#115]
Given that `trailblazer-rails` doesn't include `reform-rails` as dependency
And I have `run Song::Operation::New` in the controller
And I have `simple_form_for @form` in the view file
When I run it
Then I see an error `undefined method 'to_key'`

Adding `reform-rails` to gemfile resolved that problem. 

Shouldn't it be included by default? Any reason why it wasn't?

**Comment by emaglio** [comment]
@mmhan this is not an issue - reform and TRB are 2 different things and can be used separately so you need to specify reform gems in your application.

**Comment by mmhan** [comment]
Thanks for the clarification.
