### ISSUE TITLE
[REQUEST] `run` should provide kwargs

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-rails#123]
Currently, you can use `run` to invoke an operation in a controller. If it's successful, the passed block will be invoked and receives the `result` or `ctx` object from the run operation. http://trailblazer.to/2.1/docs/trailblazer.html#trailblazer-rails-run

In endpoint, you can do something like below, which is really convenient: when the OP was run successfully, its result/ctx is passed to the block, plus the extractable keyword arguments are passed to the block.

```ruby
run Song::Operation::Create do |ctx, model:, **|
```

Using keyword arguments also provides a stronger interface to the rendering.

**Comment by pedroaugustofsilva** [comment]
I'm implementing this enhancement. Is there a need to make the two ways (with and without extractable keywords) compatible?

I ask this because of the need to use **\*\*** to ignore the unextracted keywords on block arguments. If it is not ignored, it'll generate  `ArgumentError (unknown keyword: [any keyword forgot])`.

**Comment by apotonick** [comment]
Hey @pedroaugustofsilva :heart: in `#run`, you need to check the `arity` of the block passed to `#run`. If `arity == 1` it means the user doesn't expect kwargs. The else case handles passing ctx plus kwargs to the block: https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/controller.rb#L13 You need to add `run(.., &block)` to find out the arity.

**Comment by apotonick** [comment]
Your second question: You simply call `Result.to_h` and pass that as kwargs to the block: https://github.com/trailblazer/trailblazer-operation/blob/master/lib/trailblazer/operation/result.rb#L17
