### ISSUE TITLE
In 2.4.1 `run` doesn't return the ctx in case of a failure outcome

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-rails#126]
Prior to #124 the `Controller#run` method would return the `ctx` object. We don't have tests for that, either.

Here's the offending line https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/controller.rb#L15

**Comment by pedroaugustofsilva** [comment]
@apotonick Returning the `result` variable in this line is enough?
