### ISSUE TITLE
Engine concepts are not loaded

### ISSUE THREAD

**Issue by rosskevin** [trailblazer/trailblazer-rails#14]
@related https://github.com/apotonick/trailblazer/issues/30#issuecomment-165957356
@related https://github.com/apotonick/trailblazer/issues/71

This is failing for us on `rake db:seed`

We had a workaround for 0.1.6 that [overrode this code](https://github.com/trailblazer/trailblazer-rails/blob/5a3d88ce9dd14cff1be8aae331f7d2284c8f164b/lib/trailblazer/rails/railtie.rb):

```ruby
module Trailblazer
  class Railtie < ::Rails::Railtie

    def self.autoload_operations(app)
      # for trailblazer, requiring all files in AfCore's concept directory
      Dir.glob("#{AfCore::Engine.root}/app/concepts/**/*.rb").each do |c|
        require_dependency(c)
      end
    
      # for trailblazer, requiring all files in main app's concept directory
      Dir.glob("#{app.root}/app/concepts/**/*.rb").each do |c|
        require_dependency(c)
      end
    end
    
    def self.autoload_cells(app)
      # doing nothing here, we loaded all the cells in the concepts dir and don't want the railtie loading them again
    end
  end
end
```

This stopped working as we updated to the latest 0.2.4.  I attempted the following with no luck:

```ruby
module Trailblazer
  class Railtie < ::Rails::Railtie

    def self.load_concepts(app)
      Loader.new.(insert: [ModelFile, before: Loader::AddConceptFiles]) { |file|
        require_dependency("#{AfCore::Engine.root}/#{file}")
      }

      Loader.new.(insert: [ModelFile, before: Loader::AddConceptFiles]) { |file|
        require_dependency("#{app.root}/#{file}")
      }
    end
  end
end
```

Passing debug to the loader yields:
```
[]
[]
```

What can I do to get our engine concepts loaded so `db:seed` has access?  Or am I missing something?

**Comment by rosskevin** [comment]
It appears the Loader has no concept of base directory, so Glob always runs in the context of the startup dir.

This hack is currently working, but it would be nice if we didn't have to hack this in place:

```ruby
module Trailblazer
  class Railtie < ::Rails::Railtie

    def self.load_concepts(app)

      Dir.chdir(AfCore::Engine.root) do # Loader has no concept for base dir, must chdir so that it can find files
        Loader.new.({debug: true, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
          require_dependency("#{AfCore::Engine.root}/#{file}")
        }
      end

      Loader.new.({debug: true, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
        require_dependency("#{app.root}/#{file}")
      }
    end
  end
end
```

**Comment by rosskevin** [comment]
Updated dynamic solution for all engines:

```ruby
module Trailblazer
  class Railtie < ::Rails::Railtie

    def self.load_concepts(app)

     engines = ::Rails::Engine.subclasses.map(&:instance)
     engines.each do |engine|
       Dir.chdir(engine.root) do # Loader has no concept for base dir, must chdir so that it can find files
         Loader.new.({debug: true, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
           require_dependency("#{engine.root}/#{file}")
         }
       end
     end

      Loader.new.({debug: true, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
        require_dependency("#{app.root}/#{file}")
      }
    end
  end
end
```

**Comment by rosskevin** [comment]
I found one issue with the above during testing, the following ensures the file context for both engines and app:

```ruby
module Trailblazer
  class Railtie < ::Rails::Railtie

    def self.load_concepts(app)

      engines = ::Rails::Engine.subclasses.map(&:instance)
      engines.each do |engine|
        Dir.chdir(engine.root) do # Loader has no concept for base dir, must chdir so that it can find files
          Loader.new.({debug: false, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
            require_dependency("#{engine.root}/#{file}")
          }
        end
      end

      Dir.chdir(app.root) do  # necessary to guarantee context for tests
        Loader.new.({debug: false, insert: [ModelFile, before: Loader::AddConceptFiles]}) { |file|
          require_dependency("#{app.root}/#{file}")
        }
      end
    end
  end
end
```

**Comment by rosskevin** [comment]
For watchers - updated code in #30 as a workaround for STI model resolution.

**Comment by apotonick** [comment]
The thing I don't understand is: if your company/team does have a "work-around", why don't you get in touch with me earlier to incorporate that into the gem itself? I am not Jesus, I can't magically guess what's missing in the gems and come up with well-tested, battle-proof solutions for all the problems you guys experience from these free libraries.

**Comment by rosskevin** [comment]
I filed this issue 5 months ago immediately when I bumped into it. This issue has had no feedback from you.

I added a comment here for watchers in cases they had used the solution i posted above. I bumped into the STI problem and came up with the STI workaround yesterday and immediately posted it.  

Am I guilty of something for trying to share problems/workarounds with others?  That's what I got from your comment.

Please look at the issues I file. They state the identification and a workaround if I find one. If I'm confident it is a good solution, I submit a PR, if not, I submit my code for context in the issue looking for feedback. I do more than my part in open source.

I'm happy to submit a PR, but without feedback,  I don't know if it is an acceptable solution or if the code should live in a different gem.
