### ISSUE TITLE
Rails 5 Deprecation warning

### ISSUE THREAD

**Issue by arfl** [trailblazer/trailblazer-rails#17]
The method `ActionDispatch::Reloader.to_prepare` used [here](https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/railtie.rb#L19) is deprecated and writes the following deprecation warning to the log `DEPRECATION WARNING: to_prepare is deprecated and will be removed from Rails 5.1 (use ActiveSupport::Reloader.to_prepare instead)`

**Comment by timoschilling** [comment]
work around:
```ruby
if defined? ActiveSupport::Reloader
  ActiveSupport::Reloader.to_prepare(...)
else
  ActionDispatch::Reloader.to_prepare(...)
end
```

**Comment by apotonick** [comment]
PR? :fire_engine:

**Comment by timoschilling** [comment]
is in work

**Comment by timoschilling** [comment]
@arfl please test #18

**Comment by arfl** [comment]
@timoschilling Would work if you change `...` to `app` :-). But it is probably a better aproach to check for the version of rails, so when you drop support for a particular one, you exactly know the affected version... In your implementation, you have to rely on the comments to know whether you can delete this check or not... The propability is very high, that it stays forever ;-)

**Comment by sbleon** [comment]
This was resolved by #22 and should be closed.

**Comment by apotonick** [comment]
@sbleon Go on like this and you will have admin rights on these repos, soon! :wink:

**Comment by sbleon** [comment]
@apotonick thanks! I’m glad to be helpful!
