### ISSUE TITLE
undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by mbajur** [trailblazer/trailblazer-rails#20]
I'm trying to make a pretty basic thing withtrailblazer in one of my rails apps. Here is an operation i'm trying to use:

```
require "reform/form/validation/unique_validator"

class Page::Create < Trailblazer::Operation
  contract do
    property :name, validates: { presence: true }
    property :facebook_id, validates: { unique: true, allow_blank: true }
    property :user_id, validates: { presence: true }
    property :address, validates: { presence: true }
  end

  def process(params)
    @model = Page.new
    @model.user_id = params[:user].id

    validate(params[:page], @model) do |f|
      f.save
    end
  end
end
```

I want to make a "new" page with empty form. Following trailblazer guide, i've change contents of my old "new" action to:

```
def new
  form Page::Create
end
```

But app throws `undefined method 'name' for nil:NilClass`. The only _unusual_ thing in my app is that controller is in a mountable engine and in namespace. Here is a full stacktrace: https://gist.github.com/mbajur/d1164d534c7223771384d032686c340e

Thanks in advance for any clues!

**Comment by apotonick** [comment]
That's not how it works. :wink: The `form` helper will call `Operation#new` and *not* invoke `process` at all, which is the whole point about using `form` not `run` in the endpoint. You have to override `Operation#model!` or use `Operation::model`. http://trailblazer.to/gems/operation/model.html
