### ISSUE TITLE
Allow dry-validation to load

### ISSUE THREAD

**Issue by apotonick** [trailblazer/trailblazer-rails#23]
Per default, `trailblazer-rails` includes `ActiveModel::Validations` into `Reform::Form`:

https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails.rb#L23

It would be cool if we had a config flag, e.g.

`Trailblazer.config.validation_engine = Reform::Form::Dry`

that would monkey patch the form base class via a Railtie.

**Comment by chrkau** [comment]
Correct me if I'm wrong but doesn't that line just fix `model_name` for `Reform::Form`? And wouldn't it be enough to define reform-rails as a dependency of trailblazer-rails as it already handles the configuration of ActiveModel vs Dry validations?

**Comment by apotonick** [comment]
Now, yes, you're right! Very good point! I am expecting your PR. :beers:

**Comment by onemanstartup** [comment]
Is it not just like 
`
spec.add_dependency "reform-rails", ">= 0.1.3"
`
in gemspec and note in readme about configuration for reform-rails? I almost every time fear to make PR like that. It's more about vision and not fixing or adding features.

**Comment by apotonick** [comment]
This dependency requirement is absolutely legit! :beers:

**Comment by apotonick** [comment]
Now documented here: http://trailblazer.to/guides/getting-started.html
