### ISSUE TITLE
Operation don't return errors

### ISSUE THREAD

**Issue by ASnow** [trailblazer/trailblazer-rails#28]
There is some stub that overwrite `concept.errors`:
https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/operation/responder.rb#L15

**Comment by apotonick** [comment]
Yeah, we were talking about it a few days ago - do you want to replace it with `operation.errors` (incl. a test)?  :grimacing:

**Comment by ASnow** [comment]
Yes. `operation.errors` will be nice. Default HAL responder just return json with: `{errors: [1]}`. It's real pain for development env and break some error handling logics for production.

**Comment by v-kolesnikov** [comment]
How can I work around this issue now? This really upsets me when I am so close to building a good api using a trailblazer.

**Comment by apotonick** [comment]
Haha, it's basically

```ruby
def errors
  contract.errors
end
```

I will push it later.
