### ISSUE TITLE
No `cell` view helper

### ISSUE THREAD

**Issue by ramontayag** [trailblazer/trailblazer-rails#29]
On `v0.0.6`.

I get an undefined method. I installed `cells-rails` to add this. Should this gem require `cells-rails` instead of merely `cells`? Or perhaps the instructions should say to install `cells-rails` too?

**Comment by apotonick** [comment]
It's not that simple, unfortunately, since some people use trailblazer-rails without cells, e.g., for API-only projects. However, I tried to clarify it here: http://trailblazer.to/guides/getting-started.html#installation

**Comment by apotonick** [comment]
I am thinking about a "make-me-a-Gemfile" generator for Trailblazer, though, which will produce a Gemfile for the features you want to have included. Are you good with JS?

**Comment by ramontayag** [comment]
Sounds like overkill? :) If it can be solved by copying and pasting like you showed, better to not have code to maintain. Let me see - I'll attempt to modify the readme to make it slightly harder to not gloss over.

**Comment by apotonick** [comment]
Nope, especially since TRB works with so many different environments and ORMs, etc., this would totally make sense.
