### ISSUE TITLE
contract property name open cause error

### ISSUE THREAD

**Issue by JZO** [trailblazer/trailblazer-rails#32]
Hi.

I am encountering the following error " ArgumentError: wrong number of arguments (given 0, expected 1+)".

The error is thrown from  "validate(params[:taskroll])" call in an operation having contract with property "open".  When I rename property to "opened" and create attribute_alias in the model then It works - validation passes and the error is not thrown.

I use active record validation (not dry). Rails 5.0.

It seems to me weird I am wondering it is some name conflict in trailblazer.

Would you please advice me how to fix the issue?

Thank you.

Jiri

----- operation example code below.
  class Taskroll::Create < Trailblazer::Operation
    include Model
    model Taskroll, :create

```
contract do
  #if the property renamed to opened then it works -> validation pass and error is not thrown
  property :open
end

def process(params)
 #the error is raised from validation
  validate(params[:taskroll]) do
    contract.save
  end
end
```

  end

**Comment by apotonick** [comment]
This is an issue with the `Kernel#open` method, could you post this issue in Reform, please?
