### ISSUE TITLE
Conflict of names when using Trailblazer in Rails Engine

### ISSUE THREAD

**Issue by jurrick** [trailblazer/trailblazer-rails#34]
Hello @apotonick !

I have a problem with my Engine on Trailblazer =)

There are some trb operations in application and now I have to move them to Rails Engine. There is a problem about name conflict for class 'Callback'.

I have created an example for you: https://github.com/jurrick/trb-samples . See readme.md for further instructions.

Shortly:

 1. When you have an ActiveRecord model named Message in app and are **not** using Trailblazer for it:

    ```ruby
    Message::Callback
    # => ActiveSupport::Callbacks::Callback
    ``` 

 2. When you use Trailblazer in app:

    ```ruby
    Message::Callback
   # => Message::Callback
   ```

 3. When model and Trailblazer operations, callbacks, etc are in an engine:

    ```ruby
    Trb::Engine::Message::Callback
    # => ActiveSupport::Callbacks::Callback
   ```

I think there might be a problem about the order in which those classes are loaded while using Engine.

An expert opinion is welcome.

**Comment by apotonick** [comment]
Do you define `Callback` anywhere?

**Comment by jurrick** [comment]
`Callback` was defined only there https://github.com/jurrick/trb-samples/blob/master/trb-engine/app/concepts/trb/engine/message/callback.rb

**Comment by jurrick** [comment]
This was recently solved in `master` branch.

When I try the same in `master` then I get expected result:

```ruby
Trb::Engine::Message::Callback
# => Trb::Engine::Message::Callback
```

Then I close this issue.

PS: For last stable version (0.3.2) I have found solution by using [`require_dependency`] like this:

```ruby

module Trb::Engine
  class Message::Create < Trailblazer::Operation
    include Model, Callback
    model Trb::Engine::Message, :create

    require_dependency Trb::Engine.root.join 'app/concepts/trb/engine/message/after_save'
    callback :after_save, Trb::Engine::Message::Callback::AfterSave

    ...
```

[`require_dependency`]: http://guides.rubyonrails.org/autoloading_and_reloading_constants.html#require-dependency

Thank you.
