### ISSUE TITLE
Compatibility issues with trailblazer master

### ISSUE THREAD

**Issue by lukeasrodgers** [trailblazer/trailblazer-rails#35]
Trying to use this gem with trailblazer master causes a couple issues on application load.

First:

```ruby
/Users/luke/.rvm/gems/ruby-2.3.1/gems/trailblazer-rails-0.4.0/lib/trailblazer/rails.rb:14:in `<top (required)>': undefined method `contract_class' for Trailblazer::Operation:Class (NoMethodError)
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `rescue in block in require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:77:in `block in require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
        from /Users/luke/.../config/application.rb:17:in `<top (required)>'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

This appears to be due to the removal of `Operation.contract_class` (https://github.com/trailblazer/trailblazer/blob/master/CHANGES.md#di). 

Second, if that is resolved:

```ruby
/Users/luke/.rvm/gems/ruby-2.3.1/gems/trailblazer-rails-0.4.0/lib/trailblazer/rails.rb:24:in `<top (required)>': uninitialized constant Trailblazer::Operation::Model::DSL (NameError)
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:100:in `rescue in block in require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:77:in `block in require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `each'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler/runtime.rb:70:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1@global/gems/bundler-1.12.5/lib/bundler.rb:102:in `require'
        from /Users/luke/.../config/application.rb:17:in `<top (required)>'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `require'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:88:in `block in server'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:85:in `server'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /Users/luke/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

This appears to be because in trailblazer commit 4b47113b8d0020cf37f01fff27240c70803c9770, the DSL module was removed from `Trailblazer::Operation::Model`. 

A fix for the former is straightforward enough, though I'm not sure if it would break backward compatibility. I'm happy to open a PR for these issues, but I suspect more changes are necessary for trailblazer master/2.0 compatibility, and I'm not sure what the roadmap is for this gem with respect to master/2.0 compat vs. backwards-compat.

cheers

EDIT

this is also an issue with trailblazer 1-2 branch

**Comment by apotonick** [comment]
Fixed in 1.0.

**Comment by KurtRMueller** [comment]
What if developers are not ready to upgrade to Trailblazer 2.0? It seems like TB 2.0 has a lot of breaking changes. Anything we can do?

**Comment by apotonick** [comment]
`trailblazer-rails` 1.0 is only for TRB2 - is that what you mean, @KurtRMueller ?

**Comment by KurtRMueller** [comment]
Hi @apotonick, yes I was checking the dependencies for `trailblazer-rails` 1.0 and it requires at least `trailblazer` 2.0. I'm not ready to upgrade to tb 2.0 as I'm not ready to put in the work to update to the new api.

**Comment by apotonick** [comment]
Ah ok - the 0.4 stream is meant for TRB1.x, and the 1.0 is for TRB2. Simply stay on `~> 0.4.0`.

In a few months there might be the `trailblazer-compat` gem that allows to run TRB2 with TRB1.x code for a seamless upgrade.

**Comment by KurtRMueller** [comment]
Hey Nick. That's what I'm attempting to do. Unfortunately, I'm running into the same issue as the original poster: I get the error message `undefined method 'contract_class' for Trailblazer::Operation:Class`. Since the only solution is to upgrade to trb 2.0, I guess I'm stuck for the moment with this error.

**Comment by apotonick** [comment]
@KurtRMueller I'm confused now, you're using 

```ruby
gem "trailblazer-rails", "0.4.0" # works with TRB1.x
```

and you're on TRB 1.1, and it yet breaks with the above exception?

**Comment by lukeasrodgers** [comment]
Using trailblazer-rails 0.4 + trailblazer 1.x works fine for me.

**Comment by KurtRMueller** [comment]
@apotonick I'm sorry - I messed up. It turns out I'm the one who's confused. @lukeasrodgers is right -`trb-rails 0.4` and `trb 1.1` work just fine.

I was on `trailblazer-rails 0.3.2` (with not `trailblazer` version specification) and bumped it to `trailblazer-rails` to `0.4`. That meant that `trailblazer` got bumped to `2.0`.

I apologize for the confusion on my part and thank you all for your time. I'm really really sorry!
