### ISSUE TITLE
Not compatible with Rails 3.2.x and not explicitly documented

### ISSUE THREAD

**Issue by bjeanes** [trailblazer/trailblazer-rails#39]
[`::Rails.application.railties.find_all` is called](https://github.com/trailblazer/trailblazer-rails/blob/5bd18570ef4b1a2bab7fa16d0fdef315424d3dd9/lib/trailblazer/rails/railtie.rb#L13) to load for Rails engines, but that method does not exist in Rails 3-2-stable or below, causing a `NoMethodError` at boot time.

The gemspec only lists an _optional_ dependency for actionpack (v3.0.0 or higher) but the tests only test Rails v4.2.

What versions of Rails does this officially support? What combinations of Trailblazer gems _can_ be used with Rails 3? Is this documented somewhere?

Thanks

**Comment by apotonick** [comment]
Hi @bjeanes, what version of TRB-rails are you using?

**Comment by bjeanes** [comment]
1.0.2. I just installed it for the first time 20 minutes ago.

**Comment by apotonick** [comment]
Cool! If you find out how to retrieve a list of all engines in Rails 3.x we can merge it. This gem is the only binding to Rails, all other TRB gems work in any environment (Rails 3, Rails 2, Rails 17, Hanami, Sinatra, ...).

**Comment by apotonick** [comment]
We actually had this working in older versions of TRB-rails. Maybe come discuss here? https://gitter.im/trailblazer/chat :beers:

**Comment by apotonick** [comment]
Hey @bjeanes did you have any chance the new trb-rails in one of your apps?

**Comment by bjeanes** [comment]
Whoops, totally slipped my mind. Let me give it a shot now.

**Comment by bjeanes** [comment]
@apotonick I can boot the app now at least. I'll obviously have to try something a bit more substantial to know if there are other issues, but at least I'm able to do that now. I'll close for now and re-open if I run into anything else or open a new issue, as appropriate.
