### ISSUE TITLE
Why is @form returning a Trailblazer::Rails::Form instead of a Reform::Form contract

### ISSUE THREAD

**Issue by mensfeld** [trailblazer/trailblazer-rails#44]
when I use run I have an assignment inside @form however it is my contract wrapped with a delegator instead of having my contract. Why is that? It seems it breaks a responders gem name recognition engine for flashes.

**Comment by apotonick** [comment]
It's needed to make ActiveModel's bullshit magic work, as soon as the entire world uses formular and **not** `form_for` anymore, we can remove it. Sorry, it's the cleanest solution I could find (in TRB1, it was super hacky).

The responder probably does `FormClass.something`, tell the implementors to change that to an instance method.

**Comment by mensfeld** [comment]
shit :/ because it breaks this: https://github.com/plataformatec/responders/blob/master/lib/responders/flash_responder.rb#L174 and it seems that not wrapping works way better (at least for me and simple form). Eh... rails...

**Comment by apotonick** [comment]
That's the perfect example why library code **should never use `respond_to?`. I hate it so much and I don't understand why they still do it everywhere.

Solution: Add `Trailblazer::Rails::Form::model_name`?

**Comment by mensfeld** [comment]
@apotonick  it is not only the ```respond_to``` it is also the whole responders gem with its ```respond_with``` that uses it.

Why people use it? Because it simplifies flashes management and makes controller really, really slim especially for CRUD simple stuff. Your solution would work HOWEVER if it is on a class level, then you would have to build a class for each case (probably dynamic) which means that there will be more and more classes, which means that it will have an impact on global method cache/

**Comment by apotonick** [comment]
I meant why do people use `respond_to?`, it's the worst code pattern ever, as it says "give me an object, I'll try to guess what you want" which is pre-programmed to fail at some point. 😡

**Comment by apotonick** [comment]
No, you don't need that anonymous class, that's exactly why I introduced that `Form` wrapper - it can look up the fucking `model_name` dynamically at runtime.

**Comment by apotonick** [comment]
I'll do it if you add a super simple test with responders.

**Comment by mensfeld** [comment]
@apotonick  I know that it is not a good pattern ;)  and yes - I know that it is guessing BUT:
> You can start using Trailblazer in existing, massive applications today.
This won't happen unless people somehow can integrate Trbr at the beginning as a small part of their ecosystem (that hopefully will spread). I will try to add some specs but it will take me some it.

**Comment by apotonick** [comment]
I see what you mean, but it's impossible to "guess" where Rails uses `respond_to?` and its magic, so we **have** to run into those problems to see where they happen. I was talking about this to Patterson but he didn't understand what is the problem about `respond_to?` so I guess Rail will keep using its magic "API" until we're all sick of it. :wink:

**Comment by Tab10id** [comment]
Hm.. How about this?
```ruby
  def class
    @model_class
  end
```

Yeah.. I know I know this is a horrible hack but Trailblazer::Rails::Form is already hack. So why not?
In Rails3 `MyActiveRecordModel.scoped.is_a?(Array)` will return true because of same hack.

**Comment by siassaj** [comment]
This is strange,

When using an Operation with a Composition contract, then the models are a hash and we specify the model to use for form building within the form. But this doesn't take that into account, and so the model_name we see when using 'run' in a controller is based off of Hash.

This is weird because if we do (with a form model :foo)
@form = MyOperation::Contract.new({foo: Foo.new, bar: Bar.new}) , everything works correctly, the form builder is happy and the params hash is under 'foo' key instead of 'hash'

**Comment by n-rodriguez** [comment]
> So why do we need Rails::Form?

I wonder the same. I use [actionform](https://github.com/jbox-web/actionform) instead of Reform and I must monkey patch the `run` method to not wrap the form object : https://github.com/trailblazer/trailblazer-rails/blob/master/lib/trailblazer/rails/controller.rb#L3

**Comment by n-rodriguez** [comment]
The wrapping could happen in a separate method that people could override :

```ruby
def run_v21(operation, *dependencies)
  ...
  @form = build_tb_form(result["contract.default"], @model.class)
end

private

def build_tb_form(form, model)
  Trailblazer::Rails::Form.new(form, model)
end
```

**Comment by n-rodriguez** [comment]
Also this (http://trailblazer.to/api-docs/#trailblazer-migration-path-example-2-0-to-2-1) is not completly true since trailblazer-rails comes with reform-rails.

**Comment by apotonick** [comment]
Haha, so the Reform rip-off survived as "action form"? :joy:

@n-rodriguez Please send a PR where the wrapping happens in a separate method. Also, since in 2.1, we completely made Reform "just another optional feature", we could remove the `reform-rails` dependency.

**Comment by n-rodriguez** [comment]
> @n-rodriguez Please send a PR where the wrapping happens in a separate method. Also, since in 2.1, we completely made Reform "just another optional feature", we could remove the reform-rails dependency.

Done :)

**Comment by jtmkrueger** [comment]
So what's the fix here? Is there a way to work around this? I read all of this as ways to decouple, but don't see a solution to the issue @mensfeld brought up.

**Comment by jtmkrueger** [comment]
@Tab10id where were you sticking that?

**Comment by n-rodriguez** [comment]
> So what's the fix here?

Override `_wrap_with_trb_form` in iyour controller :

```ruby
def _wrap_with_trb_form(form, model)
  #Trailblazer::Rails::Form.new(form, model)
  form
end

**Comment by jtmkrueger** [comment]
Thanks @n-rodriguez !
