### ISSUE TITLE
undefined method `version' for Trailblazer:Module

### ISSUE THREAD

**Issue by marctich** [trailblazer/trailblazer-rails#51]
trailblazer-rails/lib/trailblazer/rails/controller.rb @ line 9

Currently is:
`      model_name, contract_name = Gem::Version.new(::Trailblazer.version) >= Gem::Version.new("2.1") ? [:model, "contract.default"] : ["model", "contract.default"]
`

Should be:
`model_name, contract_name = Gem.loaded_specs['trailblazer'].version > Gem::Version.new("2.0.9") ? [:model, "contract.default"] : ["model", "contract.default"]`

**Comment by seuros** [comment]
Fixed in master. Can you try the tests branch from now
