### ISSUE TITLE
breaking bug in ApplicationController extending when alias_method is used

### ISSUE THREAD

**Issue by bbugh** [trailblazer/trailblazer-rails#54]
We decided to try out Trailblazer in earnest, and immediately hit a blocker issue.

**Background**

We have an `alias` in `ApplicationController` that is redefining `current_user` to add extra functionality:

```
alias devise_current_user current_user
def current_user
  # ...
end
```

**Issue** 

When adding `trailblazer-rails` to the Gemfile and trying to boot, we get this error: 

```
project_dir/app/controllers/application_controller.rb:27:in `<class:ApplicationController>': undefined method `current_user' for class `ApplicationController' (NameError)
  from project_dir/app/controllers/application_controller.rb:26:in `<class:ApplicationController>'
  from project_dir/app/controllers/application_controller.rb:1:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `load'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:477:in `block in load_file'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:662:in `new_constants_in'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:476:in `load_file'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:375:in `block in require_or_load'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `block in load_interlock'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:12:in `block in loading'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/concurrency/share_lock.rb:150:in `exclusive'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies/interlock.rb:11:in `loading'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:37:in `load_interlock'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:358:in `require_or_load'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:511:in `load_missing_constant'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:203:in `const_missing'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `const_get'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:268:in `block in constantize'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `each'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `inject'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/inflector/methods.rb:266:in `constantize'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/core_ext/string/inflections.rb:66:in `constantize'
  from ~/.rvm/gems/ruby-2.2.4/gems/trailblazer-rails-1.0.4/lib/trailblazer/rails/railtie.rb:75:in `extend_application_controller!'
  from ~/.rvm/gems/ruby-2.2.4/gems/trailblazer-rails-1.0.4/lib/trailblazer/rails/railtie.rb:44:in `block (2 levels) in <class:Railtie>'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:33:in `block in on_load'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `each'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `on_load'
  from ~/.rvm/gems/ruby-2.2.4/gems/trailblazer-rails-1.0.4/lib/trailblazer/rails/railtie.rb:43:in `block in <class:Railtie>'
  from ~/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
  from ~/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
  from ~/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `call'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
  from ~/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
  from ~/.rvm/gems/ruby-2.2.4/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'
  from project_dir/config/environment.rb:5:in `<top (required)>'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
  from ~/.rvm/gems/ruby-2.2.4/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application.rb:102:in `preload'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application.rb:153:in `serve'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
  from ~/.rvm/gems/ruby-2.2.4/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from ~/.rvm/rubies/ruby-2.2.4/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:55:in `require'
  from -e:1:in `<main>'
```

**Possible fix?**

It appears that the loading system in `lib/trailblazer/rails/railtie.rb` isn't properly extending `ApplicationController`.  It looks like #11 may have been related, but it is quite out of date.

**Attempted fix**

If we comment out:

```ruby
# lib/trailblazer/rails/railtie.rb:41-45
initializer 'trailblazer.application_controller' do |_app|
  reloader_class.to_prepare do
    # Trailblazer::Railtie.extend_application_controller!(app)
  end
end
```

And manually load the modules:

```ruby
class ApplicationController < ActionController::Base
  include Trailblazer::Rails::Controller
  include Trailblazer::Rails::Controller::Cell if defined?(::Cell)
```

It works fine. 

**Summary**

It looks like when the `ApplicationController` class is forced to constantize in `extend_application_controller!`, Rails hasn't fully loaded the class, so the devise `current_user` method hasn't been defined yet. 

I would PR this, but I couldn't find consistent answer online on how this should be properly loaded.

**Comment by apotonick** [comment]
Great bug report, I wish everyone could formulate that well and concise.

Maybe a fix could be to add one of the million `:after` options to `initializer 'trailblazer.application_controller'` so this gets executed at the right time? I'm not very savvy on Rails initialization and honestly have no interest in learning more about it, but maybe @seuros knows a solution?

 By the way, be prepared to hit more immediate blockers with TRB, spring doesn't play with modern gems like Dry.rb and TRB, and the autoloading mixed with ours can lead to having to require things manually sometimes, etc etc.

**Comment by bbugh** [comment]
*"Write the bug reports that you want to see in the world."* —Gandhi 

I don't know enough about Rails initialization either, and the research I did yesterday resulted in a confusing list of things that either didn't work or were ineffective. What makes Trailblazer's loading special that it doesn't get along with autoload?

I dread returning to the hellish load times in the days before spring, is it possible (and easy?) to use Trailblazer **well** without `trailblazer-rails`? I personally would rather use manual includes if that's all that it takes.

**Comment by bbugh** [comment]
And dropped the temperature of the Earth! Move over Al Gore, we're cloning Genghis Khan to solve climate change.

Rubocop stubbornly complains about `alias_method`, but I did managed to break the law and try `alias_method` instead. I also tried putting it into a module and `include`-ing, which also didn't work. 

I expect that a `prepend` might work, but prepend sucks when you need to call the original method outside of the prepended method (`method(:current_user).super_method.call()`), and at that point we're writing weird code to work around what seems like a library bug (sorry 🤞).

**Comment by seuros** [comment]
@bbugh can you provide me with a small stripped app that reproduce the bug please.  I will fix the issue in the gem .

I have added the alias in one of my application and there is no failure.

Thanks

**Comment by apotonick** [comment]
The easiest way would be to drop including the module automatically. It's a lot of code and configuration to save the developer **one line of code in `ApplicationController` and results in issues like this. :thinking:

**Comment by apotonick** [comment]
@bbugh  The problems with spring have nothing to do with `trailblazer-rails`, they simply don't reload our classes cleanly which results in class instance variables not getting cleared, double steps, etc. I know that the DRY.rb gems have the same problem, so we concluded it's spring and not our fault (because we just use normal Ruby).

We're still investigating in what is the best way to reload environments in development (it works fine for most). Our loader simply requires all files "it knows", so you should be fine with it. I think that the loader hasn't to do anything with spring, but spring is built for Rails and as always this works with Rails-only code, only. :wink:

**Comment by apotonick** [comment]
@bbugh In case you got problems with spring, let us know. I can have a quick look into spring (if that's even possible hahaha)

**Comment by sadjow** [comment]
@apotonick the `double steps` always happens when using development auto-reloading **even without spring**. Actually, it repeats the operation's code more and more times for each changes we do in the file and reload the app in the browser. From tests and prod environment we are ok because we do not use code auto-reload.

**Comment by bbugh** [comment]
@seuros here's a simple one: https://github.com/bbugh/trb-rls-omg All I did was add devise and trailblazer-rails, along with an alias in `ApplicationController`. If you comment out the code in the controller it works, or if you comment out `trailblazer-rails` from the `Gemfile`, it works. As is, it's broken with the error I described in the original comment. 

@apotonick Thanks for explaining the issue with spring, seems reasonable. I'll most definitely post A+ bug reports if I run into anything.

**Comment by apotonick** [comment]
@sadjow Really? That happens without spring? Then we should investigate. We don't have this problem here, are you using anything "crazy"?

**Comment by seuros** [comment]
@bbugh  can you try the v1 branch ? We will release 1.0.5 if everything in your side is fine.

**Comment by bbugh** [comment]
It does not work, same error. I tested it in https://github.com/bbugh/trb-rls-omg like so:

```
# Gemfile
gem 'trailblazer-rails', github: 'trailblazer/trailblazer-rails', branch: 'v1'
```

However, I get the same error. Confirmed that it's using the correct sha1 629cd0c3cbfa: 

```
from .../gems/ruby-2.4.0/bundler/gems/trailblazer-rails-629cd0c3cbfa/lib/trailblazer/rails/railtie.rb:73:in `extend_application_controller!'
from .../gems/ruby-2.4.0/bundler/gems/trailblazer-rails-629cd0c3cbfa/lib/trailblazer/rails/railtie.rb:43:in `block (2 levels) in <class:Railtie>'
```

**Comment by bbugh** [comment]
Here's how Devise works:

1. Devise helpers [are included via an `ActiveSupport::Concern`](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/controllers/helpers.rb) 
2. which are then [autoloaded in a Controllers module](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise.rb#L22)
3. at some point that module is [loaded in a railtie](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise/rails.rb#L20)
4. which [calls ActiveSupport.on_load(:action_controller)](https://github.com/plataformatec/devise/blob/f39c6fd92774cb66f96f546d8d5e8281542b4e78/lib/devise.rb#L447) to include the helpers

Which lead to PR #55 that I believe fixes the issue. It works for me in both of my applications. I tested that `run` is available in a random controller, and it is.

**Comment by apotonick** [comment]
@seuros Maybe we version the new release 2.1.0 ?

**Comment by bbugh** [comment]
@seuros v1 branch appears to be working for us now! Nice. 👍

**Comment by sadjow** [comment]
@apotonick  The problem happens when we do an edition in a file in development mode. For each edition and save we do to a operation it runs the operation one more time. 

I thought it was `bootsnap` gem. But I removed it and the problem persists. I also tested with and without `include Trailblazer::Rails::Controller`, with and without using the `run` method.

The next step is to test in a new rails project. The steps to reproduce are:

1. Create an endpoint that executes an operation using `Rails.logger.info "executing operation"` in a step. Using `run` or `.call`.
2. Start the project in development environment
3. Access the endpoint in the browser.
4. Touch the operation's file (open and save it).
5. Access the endpoint again.
6. You can see executing operation twice in the action's logs
7. Repeat step 4.
8. You can see "executing operation" 3 times in the action's logs.

**Comment by bbugh** [comment]
Huzzah!
