### ISSUE TITLE
I didn't create Modelless form

### ISSUE THREAD

**Issue by kbaba1001** [trailblazer/trailblazer-rails#8]
I try to create modelless form `app/concepts/session/crud.rb`:

``` ruby
module Session
  class SingIn < Trailblazer::Operation
    contract do
      property :email, virtual: true
      property :password, virtual: true
    end
  end
end
```

but raise next error:

```
/bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `load': No such file to load -- /myapp/app/models/session (LoadError)
        from /bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:457:in `block in load_file'
        from /bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:647:in `new_constants_in'
        from /bundle/gems/activesupport-4.2.4/lib/active_support/dependencies.rb:456:in `load_file'
        ...
```

I use rails 4.2.4, trailblazer-rails 0.1.6.

Maybe relate to https://github.com/trailblazer/trailblazer-rails/blob/v0.1.6/lib/trailblazer/rails/railtie.rb#L10

**Comment by apotonick** [comment]
Yeah, I know, the Railtie loading is something I implemented as a quick hack. We are working on a better, more explicit loading _configuration_ (yes, configuration over convention for this problem).

Can you join https://gitter.im/trailblazer/chat so we can discuss your requirements?

**Comment by konung** [comment]
@kbaba1001  - can you try using this PR - https://github.com/trailblazer/trailblazer-rails/pull/9#partial-pull-merging 
I changed how autoloading works. 

or you can just try this 
````code
gem 'trailblazer-rails', github: 'konung/trailblazer-rails'
````

**Comment by rared** [comment]
Not sure if this helps, but your class name is misspelled (ng -> gn). Could be referencing that incorrectly somewhere else perhaps?

**Comment by kbaba1001** [comment]
@konung Think you!!
I tried your brunch. I could load `app/concepts/session/operation.rb`.

@rared I'm ashamed :sweat:
However, this typo was unrelated.

**Comment by apotonick** [comment]
I will push a new version soon with `trailblazer-loader` that should be able to do all that.

**Comment by kbaba1001** [comment]
I see. I wait new version
