### ISSUE TITLE
Reform::Form ::model getting clobbered.

### ISSUE THREAD

**Issue by exegete46** [trailblazer/trailblazer-rails#82]
In trying to build out a new system, I've continually run into issues where `Trailblazer::Rails::Form#model_name` is not honoring the `::model` set up in `Reform::Form`.  As an example, I'm setting up a Checkout form which also populates the user's profile:

```ruby
class Checkout::Contract::Create < Reform::Form
  include Profile::Contract::CreateForm
  property :nonce, virtual: true
  model :checkout
end
```
My route to the `CheckoutController#create` is `cart_checkouts_path`, but `form_for` ends up trying to use `cart_profiles_url`.  To get around this, I've had to add `@form = @_result['contract.default']` to my controller actions.  YUCK.

I question if `Trailblazer::Rails::Form#model_name` even needs to exist, but I'm sure it cannot just be removed as other projects probably rely on the functionality by now.  Instead, I propose something like the following (super hacky because it depends on implementation details, but not sure how else to accomplish):

```ruby
def model_name
  if __getobj__.class.model_options
    __getobj__.model_name
  else
    ::ActiveModel::Name.new(self, nil, @model_class.to_s.camelize)
  end
end
```
This should allow existing `Reform::Form`s to keep working as they do today, but allow the use of `::model` moving forward.

**Comment by apotonick** [comment]
@exegete46 The `Rails::Form` class only exists for Reform objects that do _not_ have `::model` set - which happened in many cases and we got so many "bug" reports via `form_for` that we decided to hack it. This PR allows you to turn off the wrapping https://github.com/trailblazer/trailblazer-rails/pull/84
